services:
    nacholibre.admin.bundles.extension:
        class: nacholibre\AdminBundle\Twig\BundleExists
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    namer.news:
        class: nacholibre\AdminBundle\Utils\VichNamer
        tags:
            - { name: namer }
#    nacholibre_admin.example:
#        class: nacholibre\AdminBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
