services:
    nacholibre.admin.bundles.extension:
        class: nacholibre\AdminBundle\Twig\BundleExists
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    namer.news:
        class: nacholibre\AdminBundle\Utils\VichNamer
        tags:
            - { name: namer }

    image_upload.subscriber:
        class: nacholibre\AdminBundle\EventListener\ImageUploadSubscriber
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_subscriber, connection: default }
#    nacholibre_admin.example:
#        class: nacholibre\AdminBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
